### ISSUE TITLE
add the option to transform resolve and reject of redux-toolbelt-thunk created action

### ISSUE THREAD

**Issue by vzaidman** [welldone-software/redux-toolbelt#19]
currently, we can do:
```
const actionCreator = makeThunkAsyncActionCreator('aaa', fn)
dispatch(actionCreator('aaa')).then(...).catch(...)
```
and the then and catch results will be the result or error of "fn".

it would be nice if we can decide what to return in this promise.

an initial implementation is available here:
https://github.com/welldone-software/redux-toolbelt/tree/transform-promise-results

but it has to be tested, documented and maybe improved.

**Comment by Satyam** [comment]
@vzaidman Please consider restoring the `transformResolve` and `transformReject` options.

Sometimes you don't want the error to propagate beyond dispatching a `xxxx.failure.TYPE` action.

For example: I have an app where after a timeout, a user might get logged out from the server and further requests rejected with a `401 Unauthorized` HTTP status code.  This is an expected error and I have reducers in place to handle this. 

A 401 HTTP error simply changes the status of the user in the store to logged off.  This is handled via a reducer.  I don't need it to propagate further.   I don't want to wrap each and every action dispatched in a try-catch block and check for that 401 code. I do want other errors to be thrown. 

These options would be a great hook to differentiate expected (for example 401) from unexpected (such as 5xx) errors.

Thanks

**Comment by vzaidman** [comment]
Hello, I'll discuss it with my team.

**Comment by Satyam** [comment]
Thanks,

I failed to point out that in the example I have of the 401 error, it might happen in absolutely any transaction, at any stage.  That is why a centralized place to handle it is crucial instead of adding exception handlers on each and every possible transaction.

As an extra, calling the two [`transformXxx`](https://github.com/welldone-software/redux-toolbelt/commit/b60023f139b129ba54faf515c8f292133a6baabe#diff-a88c3f50fa6d2c889f5492b9ca23de4cR38) functions might be done in separate `.then` and `.catch` functions as this would allow the `transformResolve` method to reject an otherwise successful HTTP response and still be caught by `transformReject`.  There are backend servers where errors are sent as data in a normal 2xx response.  Admittedly, this could easily be handled in a wrapper around the `asyncFn` function.
